In [10]:
import numpy as np

In [35]:
a = np.arange(6).reshape(3, 2)
b = np.arange(8).reshape(2, 4)
result = np.dot(a, b)
print(result)
np.max(result)


[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


47